# Generated by Django 4.2.15 on 2024-08-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_stripe_checkout_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bank_transfer_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
