# Generated by Django 4.2.15 on 2024-08-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image_url',
            field=models.URLField(default='https://picsum.photos/200'),
        ),
        migrations.AddField(
            model_name='course',
            name='lecturer',
            field=models.CharField(default='[Unknown]', max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(default='Beginner level', max_length=200),
        ),
        migrations.AddField(
            model_name='course',
            name='study_time',
            field=models.TextField(default='20 hours'),
        ),
    ]
