# Generated by Django 4.2.15 on 2024-08-25 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_image_url_course_lecturer_course_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image_url',
            field=models.URLField(default='https://picsum.photos/200', max_length=500),
        ),
    ]
