# Generated by Django 4.2.15 on 2024-08-25 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='lecturer',
            field=models.CharField(default='[Unknown]', max_length=500),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(default='Beginner level', max_length=100),
        ),
    ]
